spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.77.72:3306/appult_test?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.lll.quartz.entity.pojo